
import userimage from "../../public/icon.png"

export const tags = [
    "UI Design", "UX Design", "Web Development", "AI Tools", "Mobile Design"
  ];


export const RecentPost = [
    {
      id: 1,
      image: "https://images.unsplash.com/photo-1557800636-894a64c1696f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "UI vs. UX: What’s the difference?",
      description: "UI vs. UX: What’s the difference?",
      time: "9 August 2022",
      descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
      Category:["Desgin", "Event","PhotoGraphy","Uncategorized","React Native"],

    },
    {
      id: 2,
      image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "UX design is shifting towards realism",
      time: "9 August 2022",
      descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 3,
      image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "Best Tools to Collect Design Inspiration for Designers",
      time: "9 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 4,
      image: "https://images.unsplash.com/photo-1509474520651-4870a5e46c3b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "How to create a NFT project and get money",
      time: "9 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 5,
      image: "https://images.unsplash.com/photo-1517430816045-df4b7de01c0d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "Top 10 Things to Keep in Mind",
      time: "9 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 6,
      image: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "The Future of Web Development Trends in 2025",
      time: "10 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 7,
      image: "https://images.unsplash.com/photo-1527689368864-3a821dbccc34?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "Effective Ways to Improve User Engagement",
      time: "10 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 8,
      image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "Introduction to Motion Design Principles",
      time: "10 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 9,
      image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "Tips for Creating a Seamless Onboarding Process",
      time: "11 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 10,
      image: "https://images.unsplash.com/photo-1514837985205-7c4eae4a608f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "The Role of Color Psychology in Design",
      time: "11 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 11,
      image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "Accessibility in Design: Why It Matters",
      time: "12 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 12,
      image: "https://images.unsplash.com/photo-1559028012-dae7d2a2a324?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "Building Responsive Websites with Tailwind CSS",
      time: "12 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 13,
      image: "https://images.unsplash.com/photo-1555685812-4b743ac57b36?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "How to Build a Portfolio that Stands Out",
      time: "13 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 14,
      image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "Understanding Typography in Digital Design",
      time: "13 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 15,
      image: "https://images.unsplash.com/photo-1555617117-08e0473e06e0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "The Rise of AI in Graphic Design",
      time: "14 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 16,
      image: "https://images.unsplash.com/photo-1573164574395-10df0efc28a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "Mastering Figma: Tips and Tricks",
      time: "14 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 17,
      image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "Understanding Microinteractions in UX Design",
      time: "15 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 18,
      image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "Designing for Mobile: Best Practices",
      time: "15 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 19,
      image: "https://images.unsplash.com/photo-1519241047957-be31d7379a5d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "How to Conduct Effective User Testing",
      time: "16 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 20,
      image: "https://images.unsplash.com/photo-1517638851339-a711cfc20e1f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "The Importance of Wireframing in Design",
      time: "16 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 21,
      image: "https://images.unsplash.com/photo-1534438327270-a5e740d76cdd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "UX Research: Techniques for Success",
      time: "17 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 22,
      image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "How to Create Engaging Landing Pages",
      time: "17 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 23,
      image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "The Role of Animations in Modern UI Design",
      time: "18 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 24,
      image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "Common Mistakes in UX Design and How to Avoid Them",
      time: "18 August 2022",
      descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 25,
      image: "https://images.unsplash.com/photo-1548191265-d1f1e536a272?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "The Evolution of Design Systems",
      time: "19 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 26,
      image: "https://images.unsplash.com/photo-1537432376769-c28ccfa05b72?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "Key Differences Between Flat and Skeuomorphic Design",
      time: "19 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 27,
      image: "https://images.unsplash.com/photo-1487014679447-9f8336841d58?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "How to Optimize Websites for Performance",
      time: "20 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 28,
      image: "https://images.unsplash.com/photo-1551836022-0e95a02d3ede?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "Using AI Tools to Enhance Design Workflow",
      time: "20 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 29,
      image: "https://images.unsplash.com/photo-1555685812-4b743ac57b36?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "How to Leverage Social Media for Designers",
      time: "21 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
    {
      id: 30,
      image: "https://images.unsplash.com/photo-1537432376769-c28ccfa05b72?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
      description: "Developing Intuitive Navigation for Websites",
      time: "21 August 2022",
        descritpion:"Completely formulate integrated methods Globally maintain multifunctional",
      userimage:userimage,
      author:"Mad Sparrow",
    },
  ];
  